### ISSUE TITLE
Make no funciona

### ISSUE THREAD

**Issue by 3rdPix** [IIC2133-PUC/2023-2#10]
Tengo problemas con Make, no quiere funcionar :D

El primer intento de correr Make desde el directorio de la tarea me muestra múltiples errores, entre ellos:
```
File not found - *.h
File not found - *.c
FIND: Parameter format not correct
```
Este problema lo solucioné modificando un poco el Makefile respecto de cómo maneja la búsqueda de los archivos en SRC.
En particular modifiqué la sección de dependencias:
```
DEPS := $(wildcard $(SRC)/*/*.h)
HDRFILES := $(wildcard $(SRC)/*.h)
SRCFILES := $(wildcard $(SRC)/*/*.c)
OBJFILES := $(patsubst $(SRC)/*/%.c,$(OBJ)/%.o,$(SRCFILES))
```
Con esto ya no tenía problemas para encontrar los archivos, sin embargo el problema es otro: ahora intenta reconocer la aplicación como una aplicación de ventana con el error:
```
crtexewin.c:(.text+0x130): undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:35: dcchueck] Error 1
```
Intenté forzosamente explicarle que se trata de una aplicación de consola agregando `-mconsole` a las `CFLAGS` pero sigue arrojando el mismo error. He intentado buscar por todos lados qué otro problema podría haber más no logro encontrar solución.

Notar que instalé gnu make a través de Chocolatey.

**Comment by CataAlamos** [comment]
Hola! Me puedes mostrar como estas haciendo make y en que lugar?

**Comment by 3rdPix** [comment]
Solo llamo a `all` del **Makefile** a través de `make` en el directorio principal. El error que se produce es el que indiqué anteriormente.

## Directorio
![image](https://github.com/IIC2133-PUC/2023-2/assets/86542704/ac179628-8bef-4541-ae91-7437dddd2c60)

## Error
![image](https://github.com/IIC2133-PUC/2023-2/assets/86542704/43160579-67d5-4447-89e4-dc69db130be0)

**Comment by Pakarati** [comment]
Hola! @3rdPix me parece que no estás usando el ambiente de wsl. Prueba entrando wsl en tu cmd y luego intenta hacer el make (también puedes usar la extensión Remote WSL de VSCode, mucho más fácil al momento de editar y ejecutar tu tarea) :))

**Comment by 3rdPix** [comment]
No estoy usando WSL porque trabajé con Chocolatey para instalar `make`. Esto permite utilizarlo sin la virtualización... el problema no es que `make` no esté siendo reconocido como comando. Funciona como tal, sin embargo, debe haber algún problema con la estructuración del Makefile que no estoy viendo. Esto se comprueba con que pude arreglar el error que surgía con el comando `find` del Makefile original al reemplazarlo con `wildcard`. El problema que indica es que intenta entrar a través de `WinMain` (sugiriendo que busca una aplicación de ventana) en lugar de `main` a secas (la aplicación de consola que tenemos que desarrollar).

**Comment by CarloGauss33** [comment]
Hola @3rdPix El Repositorio del curso esta diseñado para funcionar bajo esquema UNIX (En particular las instrucciones del Makefile). Y es por esto que el make falla en sistema windows (Ya que los nombres de comandos son distintos u operan de distinta forma)

Si deseas utilizar MinGW y Make dentro de windows debes modificar el makefile para tus necesidades y versión específica de comandos en Powershell. Pero igualmente deberás considerar que en la corrección se realiza Make bajo esquema unix. Por lo que te recomendaría fuertemente utilizar virtualización
