### ISSUE TITLE
Duda con EQUIPAR (Parte A)

### ISSUE THREAD

**Issue by cperez20** [IIC2133-PUC/2023-2#11]
Hola, en el output para la parte de EQUIPAR se dice que debe seguir un formato del tipo: "ARTEFACTO artefacto ASIGNADO A guerreroID". El problema es que nunca nos dan más información del artefacto aparte del bonus que este produce, por lo que nose que deberia ir donde dice "artefacto" en la parte del output, debe ir el valor del bonus, debemos inventarle un nombre al artefacto o que deberia ir ahi? 

Quedo atento y muchas gracias de antemano :)

**Comment by CataAlamos** [comment]
Hola! Tuvimos un pequeño error en el enunciado! Debería retornar: 
`ARTEFACTO ASIGNADO A guerreroID`

**Comment by CarloGauss33** [comment]
Finalmente será ARTEFACTO bonusArtefacto ASIGNADO A guerreroID
