### ISSUE TITLE
Duda sobre qué es el arsenal

### ISSUE THREAD

**Issue by antonia-reyes** [IIC2133-PUC/2023-2#12]
Hola! No me queda muy claro qué es el arsenal. Es como una "lista" de números que sirven como bonus para atacar? o también los componentes del arsenal tienen algún otro atributo además del valor del bonus? Gracias de antemano!

**Comment by CataAlamos** [comment]
Hola, como bien dices el bonus del arsenal sirve para atacar. Los componentes de arsenal deben si o si tener el valor de bonus y dependiendo de como modeles tu código podría hasta tener un id o algo más. Eso depende ya más de tu criterio. 
<img width="961" alt="Screenshot 2023-08-19 at 11 35 10" src="https://github.com/IIC2133-PUC/2023-2/assets/62016215/94098cbe-dc79-4d87-a55c-a61340ad741a">
