### ISSUE TITLE
Duda t1 parte 2

### ISSUE THREAD

**Issue by aurzuav** [IIC2133-PUC/2023-2#123]
Hola! Veo que tenemos que hacer el quadtree de la imagen antes de usar alpha o compress. En base a qué debería parar la recursión de crear un nodo con 4 hijos? cuando dejo de crear hijos si no tengo nada para hacer la comparación de similitud al crear el árbol? Gracias!

**Comment by CataAlamos** [comment]
Hola! Hay varias formas de resolver la tarea, por lo que hay múltiples casos bases que puedes escoger. Te sugiero definir a ti el caso base que mas te acomode.

**Comment by CataAlamos** [comment]
Viendo tu código, lo mas probable es que estas construyendo mal el quadtree. Revisa eso bien.

**Comment by aurzuav** [comment]
Para saber si el problema que tengo está en el filtro o en el quadtree. Gracias.

**Comment by CataAlamos** [comment]
Vamos por pasos, revisa primero el quadtree y luego el filtro. Dicho eso, lo mas probable es que sea el filtro, pero si el quadtree esta malo entonces no te sirve de nada arreglar el filtro.

**Comment by aurzuav** [comment]
por eso, el quadtree debería generar la misma imagen que la base supongo. Estuve probando sin hacer ningun filtro, ni siquiera haciendo paint, la imagen base me sale distinta a la imagen de output sin modificar segun eddcmp.

**Comment by aurzuav** [comment]
dice que son diferentes en el byte 26... sin aplicar ningun filtro ni hacer paint.

**Comment by aurzuav** [comment]
ya arregle todo! gracias!!
