### ISSUE TITLE
Dudas calidad de código

### ISSUE THREAD

**Issue by MatiasMingo** [IIC2133-PUC/2023-2#13]
Hola buenas.

¿La nota también va a depender de si comentamos o no el código, de cómo nombramos las variables y funciones (cammel case o el idioma que usamos (inglés o español)) y otras cosas?.

Saludos,
Matías

**Comment by andresmoraga0** [comment]
Hola! 
Es ideal, como buena práctica, que hagas tu código lo más ordenado y legible posible. No obstante, en una primera instancia no se revisa el código (es decir, si corre todo bien, bacán). Ahora bien, si hay una situación excepcional, como una recorrección, si se hace una revisión manual.
Espero haber contestado tu duda :)
