### ISSUE TITLE
[T2 - Parte 1] Problema al modificar arrays de arrays

### ISSUE THREAD

**Issue by slawhs** [IIC2133-PUC/2023-2#137]
Hola! Tengo una duda, tengo un array de arrays declarado de la siguiente forma:
`array[a][b]`
y estoy intentando modificar ciertas entradas con un loop for que itera dos veces (ya verifiqué que los valores que quiero ingresar si se actualizan con cada iteración del for y que el for efectivamente pasa por las 2 iteraciones).
El problema que tengo es que la primera pasada del for la entrada que quiero cambiar se modifica perfectamente, pero a la segunda pasada por alguna razón el array no tiene ningún cambio respecto a su último valor.
Desde ya muchas gracias!

**Comment by slawhs** [comment]
De hecho luego intento hardcodear la modificación que quiero hacer e imprimir el array de arrays de nuevo pero no se modifica tampoco

**Comment by benjavicente** [comment]
¿No te sale un problema por como pasarse del rango de datos de `array[a][b]`?

Ve si estás tomando bien el (orden del) input y como se les dan al arreglo.

**Comment by slawhs** [comment]
efectivamente era el orden del input jajaja, muchas gracias!
