### ISSUE TITLE
Duda con EQUIPAR bonusArtefacto escuadronID guerreroID

### ISSUE THREAD

**Issue by lpalacios1** [IIC2133-PUC/2023-2#15]
Dado que equipar recibe solo escuadronID y guerreroID, que pasa si hay guerreros en 2 ejercitos distintos pero con el mismo escuadronID? o eso no se puede? 
Gracias!

**Comment by Pakarati** [comment]
Hola! @lpalacios1 eso no debería ocurrir porque los guerreros poseen ID único entre todos los guerreros, por ejemplo, sólo existe un guerrero de ID 0 entro ambos ejércitos
Mucho éxito:))
![64BA8910-3C27-44DF-BE32-47C43DDE7738](https://github.com/IIC2133-PUC/2023-2/assets/80866575/8e99b7cf-73e0-4496-a453-b17ddbc25c68)

**Comment by lpalacios1** [comment]
cierto, gracias!
