### ISSUE TITLE
Duda lectura de input

### ISSUE THREAD

**Issue by VicenteGarayR** [IIC2133-PUC/2023-2#17]
No entiendo como leer los inputs, si dentro de cada evento hay que utilizar la función fscan y ahí sacar la info, o hay que hacerlo de otra manera

**Comment by CataAlamos** [comment]
Hola! Digamos por ejemplo que queremos sacar los datos de 
`ENLISTADO guerreroID escuadronID`
Podemos hacer esto 
`
int guerreroID;
int escudaronID;
fscanf(input_file, "%d %d", &guerreroID, &escuadronID);
`
Y de esa manera podemos sacar los datos o info del evento,  espero que esto haya respondido tu duda.
