### ISSUE TITLE
Utilizacion de modulos propios

### ISSUE THREAD

**Issue by Nicolas413** [IIC2133-PUC/2023-2#18]
Hola, tengo un problema al modularizar, estoy creando un modulo ".h" para las estructuras que quiero utilizar en el main, lo que pasa es que cuando compilo el archivo para realizar debuggin, me da este error: "direccion del archivo main" undefined reference to "comando", mi duda es ¿como se permite que al compilar se acceda a estos modulos y tome las referencias para debuggear?

**Comment by CataAlamos** [comment]
Hola, digamos que tenemos estos archivos `main.c`, `estructuras.c` y `estructuras.h`

Primero nosotros creamos una función en `estructuras.c` (OJO los structs se definen en el .h), digamos que creo 
` ` ` 
#include "estructuras.h" // En esta línea le decimos que tomemos en cuenta los structs creados en el .h

Meal* create_menu() {

    Meal *meal = calloc(1, sizeof(Meal));
    meal -> price = 0;
    meal -> item_id = 0;

    return meal;
}

` ` ` 

Luego en estructuras.h , hacemos los siguiente

` ` ` 
// Funciones que si uso en el main
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

typedef struct meal {
    int item_id;
    int price;
} Meal;

Meal* create_menu();
` ` ` 

El .h lo usamos para exportar estas funciones que han sido declaradas al main. Tenemos nuestro `main.c`, si queremos llamar a las funciones que hemos creados en `estructuras.c` debemos hacer lo siguiente 

` ` ` 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#include "estructuras.h"

` ` ` 

Así deberías tener las importaciones, no se si esto resuelve tu duda
