### ISSUE TITLE
Duda con desertar

### ISSUE THREAD

**Issue by gonzaloi21** [IIC2133-PUC/2023-2#19]
Hola!
Si el guerrero con id 3 deserta. Puede volver a enlistarse otro guerrero con id = 3? 

Gracias

**Comment by gonzaloi21** [comment]
Y otra consulta: que tan bien debemos manejar los errores? por ejemplo: si un guerrero abandona, hay que tener en cuenta que este no puede atacar a otro? o no es necesario manejar este tipo de errores?

**Comment by CarloGauss33** [comment]
Hola @gonzaloi21. Puedes asumir que no se repeterian Id's para guerreros (Osea los nuevos tendran ids distintos)
Sobre lo segundo, la idea es que bajo ningun caso tu programa llegue a utilizar memoria invalida (Por ejemplo, si un guerrero abandona, realmente ha de abandonar, porque si no podría generar output incorrecto, o dar segmentation fault)
