### ISSUE TITLE
Duda sobre creacion de eventos

### ISSUE THREAD

**Issue by ibgarrido** [IIC2133-PUC/2023-2#20]
Hola! Mi duda es muy simple. Es posible utilizar mas variables en las funciones que utilice para que los eventos funcionen? (Por ejemplo que la funcion reciba un struct en particular y lo modifique). 

Saludos.

**Comment by CataAlamos** [comment]
Hola, me podrías dar un ejemplo de lo que quieres hacer. No se si te entendí bien.
