### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by JRichi99** [IIC2133-PUC/2023-2#22]
Probe este input: 
3
5
2
ENLISTAR 0 0 12 100 0 2 3
CONTEO-CAMPAL

No se que significa ese error

**Comment by FelipeQuinones** [comment]
Puede ser que te falte liberar un bloque de memoria el heap.

**Comment by rvcruz** [comment]
Hola, podrías utilizar valgrind ./dcchueck input output para tener mas información

**Comment by CataAlamos** [comment]
En C no te dan los mismos errores que en python, en vez de decirte como index error te dice segmentation fault (error de memoria). Se hace uso de valgrind para poder debug!

**Comment by JRichi99** [comment]
Hola, no entiendo muy bien el error porque no estoy indexando a nada en la linea que me dice el programa.

Estoy asignando Guerrero * p_guerrero = crear_guerrero(args),
y crear_guerrero devuelve un puntero a un guerrero. No comprendo si eso tiene problema

**Comment by JRichi99** [comment]
entre otras cosas crear guerrero hace algo asi:
 Guerrero* p_guerrero = calloc(1, sizeof(Guerrero));

**Comment by CataAlamos** [comment]
Hola! Puedes hacer push a tu repo para poder ver el código?

**Comment by JRichi99** [comment]
listo

**Comment by CataAlamos** [comment]
Hola! Tu problema es la forma que estas creando crear_guerrero, digamos que yo quiero crear un menu de tamaño N 

````

typedef struct meal {
    int item_id;
    int price;
} Meal;

int size_of_menu = N;

Menu** menu = calloc(N, sizeof(Meal*)) // Estoy creando un array de puntos del tipo Menu con espacio de memoria N 

for(int i =0 ; i < N; i++){
{
    Meal * meal = calloc(1, sizeof(Meal));
    meal -> price = 12;
    meal -> item_id = i;
    menu[i] = meal;
}
````
De esta forma puedo agregar una meal a mi menu.

**Comment by JRichi99** [comment]
Creo que entiendo lo que me comentas, mi error esta en igualar punteros?

**Comment by CataAlamos** [comment]
Tu error es la forma que estas asignando memoria con los punteros, puedes mostrar una foto de los que te retorna cuando haces valgrind?

**Comment by JRichi99** [comment]
![imagen_2023-08-20_205926102](https://github.com/IIC2133-PUC/2023-2/assets/110791645/b0d978d6-4602-46c7-a444-e8affbd7eee4)

**Comment by CataAlamos** [comment]
Claro, tienes el equivalente a un index error, estas asignando memoria que no esta alocada. Es decir, tu tienes un array de tamaño 4 pero tu estas alocando memoria en el espacio 5. 
Intenta con la forma que te mostré antes, eso debería funcionar bien en teoría.

**Comment by JRichi99** [comment]
Perdona, es que no entiendo :CC, como en donde hago los cambios, lo hago en la funcion crear_guerrero o en la asignacion que hago dentro de  la funcin enlistar. Voy a intentar hacer algo y ahi vuelvo a comentar. Gracias :))

**Comment by JRichi99** [comment]
Hola, ya solucione el problema al parecer, el problema es que estaba accediendo a un puntero nulo en otra parte del codigo. Muchas gracias.
