### ISSUE TITLE
Duda con forma de ejecutar

### ISSUE THREAD

**Issue by cperez20** [IIC2133-PUC/2023-2#23]
Hola, queria hacerles una duda básica. Al compilar con make dado el makefile que nos dieron se genera un archivo ejecutable de nombre  'dcchuek', este efectivamente se puede correr con el comando './dcchuek input.txt output.txt' pero no tiene de nombre 'executable' como se especifica en el enunciado. Entonces mi duda es si esto esta bien o el archivo en vez de llamarse 'dcchuek' debe llamarse 'executable' y al mismo tiempo poder ejecutarse con el comando './dcchuek input.txt output.txt'? 

Quedo atento a su respuesta y muchas gracias de antemano

**Comment by Pakarati** [comment]
Hola! @cperez20 Es un error que se nos pasó en el enunciado, el ejecutable efectivamente debe llamarse `dcchuek` :))

Mucho éxito!
