### ISSUE TITLE
Output en equipamiento exitoso

### ISSUE THREAD

**Issue by 3rdPix** [IIC2133-PUC/2023-2#25]
![image](https://github.com/IIC2133-PUC/2023-2/assets/86542704/629ce103-ab0c-4639-95f0-57a651561802)

Aquí, cuando indica "ARTEFACTO **artefacto** ASIGNADO A guerreroID"... ¿Qué es exactamente lo que resalto en negrilla? ¿el bonus del artefacto?

**Comment by CarloGauss33** [comment]
Hola, lo que esta en negrita no deberia ir

En la issue #11 se responde

**Comment by brayan788** [comment]
hola en los tests creo que sale un numero ahi; nose si es el bonus o realmente no va algo ahi??
