### ISSUE TITLE
Duda Traicionar

### ISSUE THREAD

**Issue by agustinbc7** [IIC2133-PUC/2023-2#26]
Hola, una duda con TRAICIONAR, ¿el guerrero que traiciona se coloca al final del escuadrón enemigo?
Gracias de antemano.

**Comment by tama0903** [comment]
Hola!

Yo asumí que se pone al final del escuadrón enemigo. Por fa, algún ayudante que lo confirme 👀👀

PD: También, hice ese mismo supuesto para el evento de ALTA-TRAICION (asi que por fiss confirmenlo).

**Comment by agustinbc7** [comment]
yaa gracias!!
