### ISSUE TITLE
Tamaño Arsenal

### ISSUE THREAD

**Issue by cperez20** [IIC2133-PUC/2023-2#27]
Hola, en el enunciado dice que el arsenal tiene una capacidad definida pero no puedo encontrar cual es esa capacidad, la dan en algún evento o falto mencionarlo en el enunciado? Quedo atento y muchas gracias de antemano

**Comment by Pakarati** [comment]
Hola! @cperez20 la capacidad se entrega junto a toda la información necesaria de un guerrero en la Parte A, en el evento `Enlistar`

<img width="602" alt="1arsenal" src="https://github.com/IIC2133-PUC/2023-2/assets/80866575/d5bf0b17-81b1-4d24-bdec-57a573936352">

Éxito:)
