### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by 3rdPix** [IIC2133-PUC/2023-2#28]
Tenemos información disponible respecto de las condiciones de ejecución final? Por ejemplo cuál es el número máximo o mínimo de escuadrones que podría tener cada ejército, el número máximo y mínimo de guerreros que podrían haber... etc?

*algo como lo que siempre nos da leet 👀*

**Comment by Dafnemami** [comment]
No va a ser un número ridículo de escuadrones. Hay algo que te preocupe en particular?

**Comment by 3rdPix** [comment]
Justamente eso, con tu respuesta fue suficiente, gracias!

**Comment by 3rdPix** [comment]
Justamente eso! Con tu respuesta fue suficiente, gracias!
