### ISSUE TITLE
Error en instalación en edd-docker para MacOS

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2133-PUC/2023-2#3]
Hola!

Estoy siguiendo los pasos del video de instalación de Docker para MacOS con el repositorio `https://github.com/IIC2133-PUC/edd-docker`. Tengo instalado docker y docker-compose. Sin embargo, en el primero paso, al hacer `make start` me aparece esto:

<img width="780" alt="image" src="https://github.com/IIC2133-PUC/2023-2/assets/62080216/34b4c73b-d70b-46d1-92ef-888202c7f141">

No puse esta issue en ese repositorio porque no había pestaña de issues

**Comment by santiernst** [comment]
Hola! Cómo solucionaste esto?? Me pasa lo mismo

**Comment by jirarrazaval** [comment]
> Hola! Cómo solucionaste esto?? Me pasa lo mismo

No tenía corriendo Docker Desktop jajaj fui muy pava

**Comment by santiernst** [comment]
Por si es que a alguien le sirve, encontré esto:
![Captura de pantalla 2023-09-04 a la(s) 15 07 57](https://github.com/IIC2133-PUC/2023-2/assets/80714848/65a8eb17-bf4d-40b7-b9a8-472c480cb8b9)
Solo cambié 

 ```
start:
    docker-compose up -d
    docker-compose exec mycontainer /bin/bash
```
por: 
```
start:
    docker compose up -d
    docker compose exec mycontainer /bin/bash
```
en el Makefile y me funcionó.
