### ISSUE TITLE
Duda Test sobre TRAICIONAR y ALTA-TRAICION

### ISSUE THREAD

**Issue by tama0903** [IIC2133-PUC/2023-2#30]
Hola!

En los eventos de TRAICIONAR y ALTA-TRAICION, el guerreroID se puede asumir que será un guerrero existente o tenemos que abordar el caso de que el id que esté en los test pueda ser de un guerrero que ya no esté en el squad o que haya sido eliminado. Lo comento debido a que revisando los test que son de letra C, hay id's de guerreros que han sido eliminados. Igualmente, se entiende si hay un error al usar varios eventos (ATACA), pero me gustaría saber si hay que considerar ese caso.

**Comment by CarloGauss33** [comment]
Si, se puede asumir que existe

**Comment by CarloGauss33** [comment]
(Los tests estaban incorrectos antes)
