### ISSUE TITLE
Inconsistencia respuesta issue #11 y outputs de prueba en evento (EQUIPAR)

### ISSUE THREAD

**Issue by 3rdPix** [IIC2133-PUC/2023-2#31]
Según se preguntó en issues anteriores. El segmento en que hay un equipamiento exitoso debe ser expuesto como
**ARTEFACTO EQUIPADO A ID**, contradiciendo lo que dice el enunciado de la tarea. Pero luego nos entregan los archivos de prueba, y en los outputs se puede apreciar como el formato de impresión **Sí** sigue aquél indicado en el enunciado (aka **ARTEFACTO BONUS EQUIPADO A ID**).

¿Cuál es finalmente la real forma en que debemos imprimir la información de este evento?

**Comment by CarloGauss33** [comment]
Hola los tests habian quedado mal subidos. Ahora se actualizaron a la ultima version

**Comment by CarloGauss33** [comment]
Finalmente será ARTEFACTO bonusArtefacto ASIGNADO A guerreroID
