### ISSUE TITLE
Inconsistencia enunciado y archivos de prueba para evento (CONTEO-CAMPAL)

### ISSUE THREAD

**Issue by 3rdPix** [IIC2133-PUC/2023-2#32]
En el enunciado nos indica que debemos imprimir la información de la siguiente forma:
![image](https://github.com/IIC2133-PUC/2023-2/assets/86542704/edee6f8a-2859-4fcf-a077-6abe0511caa7)
Respetando el formato incluso a nivel de tabs (\t). Pero en los archivos de prueba el output está de la siguiente forma:
![image](https://github.com/IIC2133-PUC/2023-2/assets/86542704/4d8a82bd-9b1f-4e0c-a18c-3a0b3d65c8a2)
La única diferencia es que *"Ejercito"* no está completamente en mayúsculas. 
¿Cuál formato debería prevalecer?

**Comment by CarloGauss33** [comment]
Hola los tests habian quedado mal subidos. Ahora se actualizaron a la ultima version
