### ISSUE TITLE
Generación de archivos con nombres de variables de mi programa

### ISSUE THREAD

**Issue by miguelsaavedra27** [IIC2133-PUC/2023-2#33]
Hola! Al compilar y correr mi tarea me pasa que se generan archivos con nombres de variables que usé en el programa. Son todos archivos de 0 bytes del tipo .file. 

![image](https://github.com/IIC2133-PUC/2023-2/assets/80911193/161b55a5-69ab-43a1-841f-e90ec3bbfa39)

**Comment by CarloGauss33** [comment]
Pregunta. ¿Como estas compilando? Con Make?
