### ISSUE TITLE
Usuario no encontrado en servidor

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2133-PUC/2023-2#34]
Hola!
Ya me registré hace mucho en https://iic2133.org/, pero ahora que el servidor está arriba, aún me sale esto:
` curl "edd.ing.puc.cl/test?repo=T0-2023-2-{mi-usuario}&branch=prueba"
Repo: T0-2023-2-{mi-usuario}
Branch: prueba
Usuario inexistente. Contactar a @cparedesr.`

Asumo que mi nombre de usuario es el mismo que el el de github

**Comment by 3rdPix** [comment]
Me ocurre algo semejante pero en lugar de usuario me indica repositorio no valido

**Comment by CarloGauss33** [comment]
Hola @jirarrazaval @3rdPix. El servidor no se encontraba habilitado a esa hora. Recientemente fue habilitado para probar
