### ISSUE TITLE
Inconsistencia en Evento ATACAR en tests

### ISSUE THREAD

**Issue by tama0903** [IIC2133-PUC/2023-2#36]
Hola!

Revisando los tests, me surgio una duda. En el enunciado, se explicita lo siguiente:
![Captura de pantalla 2023-08-24 111249](https://github.com/IIC2133-PUC/2023-2/assets/69864793/3cc36ed5-0f57-4d45-9083-e498a9c92ed0)

Pero, parece que en los tests se hace lo contrario. Para el escuadrón atacante se elige al que posee menor valor de ataque base sumado entre sus guerreros mientras que el escuadrón defensa se elige al que tiene más guerreros. A menos que, el comando ATACA ejercitoID, se refiera a que el ID no es del ejército atacante sino que sea el ejército que hay que atacar 👀. Espero que resuelvan mi duda, por fiss.

**Comment by CarloGauss33** [comment]
Hola, se actualizo una nueva version de los tests. Los mencionados tenian problemas

**Comment by tama0903** [comment]
Muchas gracias!
