### ISSUE TITLE
Testss ATACAR no dan outputs esperados

### ISSUE THREAD

**Issue by Francescorodriguezg** [IIC2133-PUC/2023-2#37]
Hola 
En el test easy B0, los outputs son los esperados cuando el comando es ATACA 0, pero cuando es ATACA 1 el guerrero atacado pertenece al ejercito 1, cosa que no hace sentido, considerando que el ejercito 1 es el atacante.

**Comment by Sebas750** [comment]
A mi me ocurre lo mismo, quedo atento. Gracias de antemano!

**Comment by CarloGauss33** [comment]
Hola los tests habian quedado mal subidos. Ahora se actualizaron a la ultima version
