### ISSUE TITLE
Inconsistencia output CONTEO-CAMPAL

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2133-PUC/2023-2#38]
Me metí al servidor y tengo incorrectos los tests tipo C. Entonces estoy probando con los tests del drive y he notado inconsistencias con el resultado de CONTEO-CAMPAL.

Por ejemplo, en el easy/C1,  sale:

```
CONTEO-CAMPAL
	EJERCITO 0
		FACCION 0: 3
		FACCION 1: 4
		FACCION 2: 7
	EJERCITO 1
		FACCION 0: 3
		FACCION 1: 3
		FACCION 2: 5
TOTAL DE GUERREROS : 25
ENLISTADO 25 12
ENLISTADO 26 6
ENLISTADO 27 14
ENLISTADO 28 9
ENLISTADO 29 15
ENLISTADO 30 3
ENLISTADO 31 12
ENLISTADO 32 12
ENLISTADO 33 1
ENLISTADO 34 3
ENLISTADO 35 5
ALTA-TRAICION 0
CONTEO-CAMPAL
	EJERCITO 0
		FACCION 0: 5
		FACCION 1: 4
		FACCION 2: 9
	EJERCITO 1
		FACCION 0: 3
		FACCION 1: 5
		FACCION 2: 11
TOTAL DE GUERREROS : 37
```

Y esto no tiene sentido ya que después del primer conteo-campal se agregan 11 soldados, por lo que el segundo conteo-campal después de ese debería sumar 25 + 11 = 36.

**Comment by CarloGauss33** [comment]
Hola @jirarrazaval Habian quedado mal subidos: Ahora se actualizaron bien

**Comment by jirarrazaval** [comment]
> Hola @jirarrazaval Habian quedado mal subidos: Ahora se actualizaron bien
Hola Carlos! Si he visto, lo he estado actualizando siempre a las versiones más recientes y en todas he encontrado una inconsistencia con el conteo-campal. La última versión que descargué del drive fue ahora recién a las 23:20

**Comment by CarloGauss33** [comment]
En cual te aparecen inconsistencias? Y Segundo, son solo en los C?

**Comment by jirarrazaval** [comment]
> En cual te aparecen inconsistencias? Y Segundo, son solo en los C?

En la de arriba! Easy/c1. Edite la issue y ahi puse el error de la nueva.

**Comment by CarloGauss33** [comment]
Hola. Los volvi a actualizar. Habia un problema en el generador que no buscaba el squad con mayor numero de miembros.

**Comment by brayan788** [comment]
Hola, tengo el mismo problema solo en los tests C y siguen existiendo inconsistencias al revisarlos manualmente.
