### ISSUE TITLE
problemas de código (segmentation fault)

### ISSUE THREAD

**Issue by LunaGarces** [IIC2133-PUC/2023-2#39]
al intentar hacer el CONTEO-CAMPAL mi codigo no entra a un bucle, y la terminal me muestra
zsh: segmentation fault 
que significa esto? me pueden ayudar para poder solucionarlo, porque el codigo en si no tira error

**Comment by benjavicente** [comment]
Puede ser algo duplicado de #22

Ese error es que estás accediendo a memoria que no te pertenece. ¿Probaste corriendo el programa con vailgrind?

**Comment by LunaGarces** [comment]
Probé haciendo debug y me tira

EXC_BAD_ACCESS (code=1, address=0x0)

pero y no se la la info se la lista que estoy pidiendo, no se muy bien como usar Valdgrin en mac, debo copiar mi código en el repo Edd-docker o como?

Sent from my iPhone

On 25-08-2023, at 12:54, Benjamín Vicente ***@***.***> wrote:

﻿

Puede ser algo duplicado de #22<https://github.com/IIC2133-PUC/2023-2/issues/22>

Ese error es que estás accediendo a memoria que no te pertenece. ¿Probaste corriendo el programa con vailgrind?

**Comment by benjavicente** [comment]
¿Viste la  [guia de setup](https://github.com/IIC2133-PUC/2023-2/blob/master/Gu%C3%ADas/Set%20Up/1.3%20Setup%20en%20Mac%20OS.md) que se mandó? También está la opción de usar [dev-container](https://github.com/IIC2133-PUC/edd-dev-container) que es algo nuevo que estamos probando.

**Comment by illanes00** [comment]
Hola @LunaGarces ! Hace poco publiqué una [guía de soluciones de problemas en tareas](https://github.com/IIC2133-PUC/2023-2/blob/master/Gu%C3%ADas/5.%20AYUDAA%20(Gu%C3%ADa%20de%20resoluci%C3%B3n%20de%20problemas%20en%20tareas).md), la cual creo que te podría ser de utilidad!

**Comment by LunaGarces** [comment]
La revisaré graciasss

Sent from my iPhone

On 25-08-2023, at 14:06, Benjamín Vicente ***@***.***> wrote:

﻿

¿Viste la guia de setup<https://github.com/IIC2133-PUC/2023-2/blob/master/Gu%C3%ADas/Set%20Up/1.3%20Setup%20en%20Mac%20OS.md> que se mandó? También está la opción de usar dev-container<https://github.com/IIC2133-PUC/edd-dev-container> que es algo nuevo que estamos probando.

**Comment by LunaGarces** [comment]
Graciasss!!

Sent from my iPhone

On 25-08-2023, at 18:51, Martín Illanes ***@***.***> wrote:

﻿

Hola @LunaGarces<https://github.com/LunaGarces> ! Hace poco publiqué una guía de soluciones de problemas en tareas<https://github.com/IIC2133-PUC/2023-2/blob/master/Gu%C3%ADas/5.%20AYUDAA%20(Gu%C3%ADa%20de%20resoluci%C3%B3n%20de%20problemas%20en%20tareas).md>, la cual creo que te podría ser de utilidad!
