### ISSUE TITLE
Duda con Enlistar (Parte A)

### ISSUE THREAD

**Issue by agustinbc7** [IIC2133-PUC/2023-2#4]
Hola, en la creación de ejércitos (ENLISTAR), al final dice: "El enlistamiento se debe realizar al final del escuadrón en posición escuadronID". ¿Esto significa que el ID del escuadrón es equivalente a su posición en el ejército? Gracias de antemano.

**Comment by CarloGauss33** [comment]
Es una opción. La verdad depende de la modelación que implementes. Lo de "Posición" Fue para dar un mini tip
