### ISSUE TITLE
Inconsistencias Tests con ALTA-Traicion

### ISSUE THREAD

**Issue by Francescorodriguezg** [IIC2133-PUC/2023-2#41]
Hola!
Estuve revisando los tests tipo C que tienen instrucciones "Alta-Traicion" y no llego a los outputs esperados. Me puse a debuggear a mano el EASY C2, y creo que está mal (se me ocurre que pasa lo mismo con los otros). Por ejemplo, en este fragmento desaparece misteriosamente un miembro de la faccion 1 del ejercito 0. Notar que la instruccion ATACA 11 76 no debiese influir, ya que el soldado id 76 es de la faccion 0 del ejercito 0. 
CONTEO-CAMPAL
	EJERCITO 0
		FACCION 0: 14
		**FACCION 1: 9**
		FACCION 2: 12
	EJERCITO 1
		FACCION 0: 16
		FACCION 1: 11
		FACCION 2: 17
TOTAL DE GUERREROS : 79
ENLISTADO 80 12
ENLISTADO 81 17
ENLISTADO 82 6
ENLISTADO 83 2
TRAICION 1
EJERCITO 1
	ESCUADRON 3 4
	ESCUADRON 6 4
	ESCUADRON 8 4
	ESCUADRON 10 4
	ESCUADRON 11 4
	ESCUADRON 16 4
	ESCUADRON 0 3
	ESCUADRON 14 3
	ESCUADRON 17 3
	ESCUADRON 1 2
	ESCUADRON 2 2
	ESCUADRON 5 2
	ESCUADRON 9 2
	ESCUADRON 12 2
	ESCUADRON 13 2
	ESCUADRON 4 1
	ESCUADRON 7 1
	ESCUADRON 15 0
TRAICION 1
EJERCITO 1
	ESCUADRON 3 4
	ESCUADRON 6 4
	ESCUADRON 8 4
	ESCUADRON 10 4
	ESCUADRON 11 4
	ESCUADRON 16 4
	ESCUADRON 0 3
	ESCUADRON 14 3
	ESCUADRON 17 3
	ESCUADRON 1 2
	ESCUADRON 2 2
	ESCUADRON 5 2
	ESCUADRON 9 2
	ESCUADRON 12 2
	ESCUADRON 13 2
	ESCUADRON 4 1
	ESCUADRON 7 0
	ESCUADRON 15 0
ATACA 11 76
CONTEO-CAMPAL
	EJERCITO 0
		FACCION 0: 15
		**FACCION 1: 8**
		FACCION 2: 13
	EJERCITO 1
		FACCION 0: 15
		FACCION 1: 13
		FACCION 2: 18
TOTAL DE GUERREROS : 82
Saludos y gracias!

**Comment by CataAlamos** [comment]
Hola! Estamos arreglando esos tests cases ahora! Deberíamos tenerlo solucionado pronto .

**Comment by Francescorodriguezg** [comment]
Bacan, gracias. A modo de complementar, aca hay otra cosa rara (ver los totales de cada conteo campal):
CONTEO-CAMPAL
	EJERCITO 0
		FACCION 0: 22
		FACCION 1: 11
		FACCION 2: 18
	EJERCITO 1
		FACCION 0: 14
		FACCION 1: 17
		FACCION 2: 23
TOTAL DE GUERREROS : 105
ATACA 48 76
CONTEO-CAMPAL
	EJERCITO 0
		FACCION 0: 22
		FACCION 1: 11
		FACCION 2: 18
	EJERCITO 1
		FACCION 0: 13
		FACCION 1: 17
		FACCION 2: 22
TOTAL DE GUERREROS : 103
