### ISSUE TITLE
Indentación en enunciado vs en soluciones del drive

### ISSUE THREAD

**Issue by arturoprietovic** [IIC2133-PUC/2023-2#44]
En el enunciado sale que es con un tab de indotación pero en los outputs de solución sale con 2.
<img width="215" alt="image" src="https://github.com/IIC2133-PUC/2023-2/assets/65640660/7d49a3a1-8513-4c32-81b1-43bed72751a9">
<img width="188" alt="image" src="https://github.com/IIC2133-PUC/2023-2/assets/65640660/72619023-aab2-4260-ba5f-cde7703d73bc">

Cual es la forma correcta?

**Comment by illanes00** [comment]
Hola! @arturoprietovic, te recomiendo usar `\t` en tu output. Aquello evita ese tipo de ambigüedades
