### ISSUE TITLE
Duda con inputs issue #17

### ISSUE THREAD

**Issue by IgnacioHqz** [IIC2133-PUC/2023-2#45]
Hola, leyendo la issue #17 no me quedó claro por qué capturan los datos de esa forma. Leyendo el codigo base, con la variable 'command' se hace un arreglo de largo 32, y luego se guarda toda la linea de evento en fscanf(input_file, "%s", command) que está dentro del for que recorre todos los eventos.
Mi duda es que si ya se tiene agregada toda la linea del evento en command, está bien que guarde las variables de la linea como sale en la issue #17? o debo guardar las variables reconociendo cuánto gasta en memoria cada cosa?
Por ejemplo, si la linea es ENLISTAR 0 1 2, para guardar el 2 sería: command[23]? (ENLISTAR: 8, Espacios: 1, numeros: 4)
No entiendo muy bien como guardarlas las variables si ya se tiene fscanf(input_file, "%s", command);
Muchas gracias!

**Comment by illanes00** [comment]
Hola @IgnacioHqz ! Al usar el formato de string `%s` en `scanf()`, este se detiene en los espacios en blanco. Por lo tanto, no se guarda toda la linea del evento, sino sólamente la primera "palabra" de la línea.

Por ejemplo, si tu archivo de texto contiene: `ENLISTAR 0 0 0 409 42 1 5`; el siguiente código debiese tener como output `ENLISTAR`. 
```c
fscanf(input_file, "%s", command);
printf("%s", command);
```
  
Si deseas seguir leyendo después de "enlistar", puedes ocupar `fscanf(input_file, "%i", siguiente_numero);` y sus variaciones (tal como dice la issue #17).

Espero que haya quedado claro!

**Comment by IgnacioHqz** [comment]
Perfecto! Entonces, si con fscanf(input_file, "%$", ...) la busqueda se detiene al encontrar un espacio en blanco dentro de la linea, la busqueda queda 'parada' dentro de la linea y no salta a la siguiente? Por lo que si luego ocupo fscanf(input_file, "%i", ...) se mueve hasta el proximo numero y si llega al final entonces la busqueda saltará a la siguiente linea?
Quedo atento, gracias!

**Comment by illanes00** [comment]
Tal cual como mencionas @IgnacioHqz! Supongo que ahi debieses tener más claridad de cómo seguir en la tarea.

Éxito!
