### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by VicenteGarayR** [IIC2133-PUC/2023-2#46]
Hola, he estado probando los test case del server, y en la parte A me sale wrong output, pero después veo mi output y no encuentro el error. Quizás me sobra/falta algún tab o algún espacio. No se si me podrían ayudar a encontrar el error, gracias

**Comment by illanes00** [comment]
Hola @VicenteGarayR! Solo para confirmar, probaste utilizar herramientas como el [comando `diff`](https://www.islabit.com/91508/como-comparar-dos-archivos-de-texto-en-el-terminal-linux.html) o [diffchecker](https://www.diffchecker.com/)?

**Comment by illanes00** [comment]
Revisé tu repositorio y sólo ocupas `printf()` y no `fprintf()` (sólo imprimes a consola y no a archivo). Como los resultados no se imprimen a archivo, el output no es correcto y se genera el *Wrong Output* 

Espero que haya quedado claro! Si te quedan dudas, puedes comentarnos por acá

**Comment by VicenteGarayR** [comment]
jajaja no sabía eso, muchas gracias
