### ISSUE TITLE
[T0] Cantidad de inputs en Desertar 

### ISSUE THREAD

**Issue by aplaza2** [IIC2133-PUC/2023-2#47]
Hola, en el enunciado se muestra que para el evento de Desertar se entregan _ejercitoID_, _escuadronID_ y _guerreroID_, pero en el los inputs de la demo solo recibe 2 parámetros:

![image](https://github.com/IIC2133-PUC/2023-2/assets/76175241/546db011-e8b6-447c-9c1c-7c66f7104797)

![image](https://github.com/IIC2133-PUC/2023-2/assets/76175241/2416d1e7-2630-445f-9cff-acd34ceadf7b)

Solo se está entregando el ejército y el guerrero, ¿se dejará con solo esos 2 o en el servidor está funcionando con los 3 inputs? Gracias de antemano.

**Comment by MatiasMingo** [comment]
Hola. Siguen habiendo errores. Como en demo/B1.txt 
![Screen Shot 2023-08-28 at 14 03 20](https://github.com/IIC2133-PUC/2023-2/assets/20389726/dd7102d1-4959-4791-bb67-72f704de90d5)

**Comment by MatiasMingo** [comment]
Hola. ¿Dónde se supone que están los tests actualizados? ¿En el drive? Por lo que veo en el drive, todavía no se actualizan. Por ejemplo, B1.txt sigue teniendo DESERTAR con 2 parámetros y no 3.

**Comment by illanes00** [comment]
Toda la razón! Se nos quedaron unos test demo sin actualizar. Borramos esos tests y puedes ocupar los otros
Gracias por avisar!
