### ISSUE TITLE
Duda con output en atacar

### ISSUE THREAD

**Issue by RaimundoRB** [IIC2133-PUC/2023-2#49]
Hola, en el enunciado dice:

> En caso de que el ataque sea mayor o igual a la vida, el guerrero defensor muere y es eliminado (Equivalente a la operación
desertar)

Como es equivalente a la operación desertar, deberíamos poner en el output `ABANDONA n n` como al desertar o solo se refiere a que en ambos casos, el guerrero deja de estar considerado en el ejercito.

**Comment by 4n1t4** [comment]
Hola, esto solo hace guiño a que debe ser eliminado del ejercito, por lo que puede ser muy parecido a tu función de desertar, pero el output que debes entregar es el respectivo solamente a atacar.
