### ISSUE TITLE
Tamaño arsenal

### ISSUE THREAD

**Issue by rvcruz** [IIC2133-PUC/2023-2#5]
¡Hola! Al instanciar a los guerreros, el enunciado dice que el arsenal tiene tamaño definido, sin embargo, no encuentro informacion sobre cual es el valor maximo explicito, tampoco entiendo el formato en que se entregan los artefactos. Atento a comentarios

**Comment by CarloGauss33** [comment]
No entiendo a que te refieres con el valor maximo explicito. El valor es fijo por guerrero. Osea uno podria tener un arsenal de 10 slots mientras que otro de 1000. (Siendo el numero maximo posible INT_MAX). Pero son distintos por guerrero. Se entrega solo un numero, que es el "Bonus" que algo entrega, no es necesario que sea un struct como tal
