### ISSUE TITLE
Alta-Traición

### ISSUE THREAD

**Issue by MatiasAPineda** [IIC2133-PUC/2023-2#50]
Hola hola, 

tengo una duda sobre el enunciado de Alta-Traición: Cuando se refiere a "**desde el guerrero señalado hacia atrás**"  se refiere desde el guerrero indicado hacia el cabecilla del escuadrón traiciona o  desde el guerrero indicado hasta la cola del escuadrón??

Gracias

**Comment by 4n1t4** [comment]
Es desde el guerrero hasta la cola:
por ejemplo tenemos el siguiente escuadrón: A-> B-> C->D
y el guerrero C realiza alta traición, entonces el escuadrón original ahora queda solamente como A->B , y los guerreros C->D deben ser conectados al ultimo guerrero del escuadrón enemigo correspondiente a lo que indica el enunciado.
Saludos !
