### ISSUE TITLE
TIMEOUT servidor

### ISSUE THREAD

**Issue by gonzaloi21** [IIC2133-PUC/2023-2#53]
Hola! 
Tengo los outputs del servidor correctos y sin leaks pero me paso en los 10 segundos de ejecución (el que mas de demora tarda 1 minuto aprox.).
Como puedo disminuir el tiempo? algún tip? o alguien que le haya pasado lo mismo que lo pudo solucionar?

gracias

**Comment by 4n1t4** [comment]
Hola, si no tienes ninguno de los otros errores, lo más probable es que tengas muchas búsquedas de O(n) en acciones innecesarias. Podrías evaluar una forma de evitar estas búsquedas si el propósito por ejemplo de estas es calcular una cantidad de algo, lo que se podría remplazar por actualizar una variable solo en caso de que hayan agregaciones o eliminaciones y otras modificaciones en algo. 
Saludos!
