### ISSUE TITLE
Forma de uso de test cases

### ISSUE THREAD

**Issue by MartinAracena** [IIC2133-PUC/2023-2#54]
Disculpen, no me queda claro si la unica forma de probar los test cases de manera automatica es por medio del servidor o si hay otra forma de correr en output para compararlo con cada una de las respuestas. Anteriormente probaba los test con los demos, pero a los demos les falta .un input en DESERTAR, dado que solo contiene 2 inputs y queria entender como usar los test cases aparte del servidor.

**Comment by CataAlamos** [comment]
Hola! Puedes correr los test cases de forma local y hacer un script sh que los corra todos por ti, pero te recomiendo hacerlo uno por uno y que hace el debugging mucho más amigable. 
Puedes usar el comando `diff output_esperado.txt output_dado.txt` con eso puedes ver si hay diferencias en los outputs.
