### ISSUE TITLE
Error al ejecutar programa

### ISSUE THREAD

**Issue by santiurzua** [IIC2133-PUC/2023-2#55]
Hola!
Mi programa pudo compilar perfecto con make, pero al querer ejecutarlo con "\. dcchueck input.txt output.txt" me sale el siguiente error y no ejecuta nada: "-bash: .: dcchueck: cannot execute binary file". Busqué en internet pero no encontré ninguna solución:(

Qué puedo hacer?

**Comment by victorllagos** [comment]
Revisa que hayas escrito bien el comando debería ser `./dcchueck input output`

**Comment by santiurzua** [comment]
Eso era. Perdón la estupidez.
