### ISSUE TITLE
Duda de inputs 

### ISSUE THREAD

**Issue by LunaGarces** [IIC2133-PUC/2023-2#57]
estaba revisando mi codigo y si bien hace los cálculos bien, no me recibe todos los inputs, por ejemplo probando los archivos c1 enlista hasta "ENLISTAR 0 73 859 465 45 2 3", pero en teoría debería seguir recibiendo inputs y ejecutando el resto de funciones, y no se cual es el problema que causa esto

**Comment by CataAlamos** [comment]
Hola! Te sugiero que revises la issue #17 ahi explico como se deben leer los inputs de forma correcta.

**Comment by LunaGarces** [comment]
Estoy leyendo de esa forma los inputs, pero luego de los primeros deja de mostrarlos en el txt

Sent from my iPhone

On 31-08-2023, at 08:15, Cata Alamos ***@***.***> wrote:

﻿

Hola! Te sugiero que revises la issue #17<https://github.com/IIC2133-PUC/2023-2/issues/17> ahi explico como se deben leer los inputs de forma correcta.

**Comment by CataAlamos** [comment]
Puedes subir tus ultimos cambios a github para ver que esta pasando?

**Comment by LunaGarces** [comment]
Tengo los cambios subidos, de todas formas me gustaría que supieras que el error me lo tira en los Test B, en los C tiene error segmentation fault

Sent from my iPhone

On 31-08-2023, at 11:36, Cata Alamos ***@***.***> wrote:

﻿

Puedes subir tus ultimos cambios a github para ver que esta pasando?
