### ISSUE TITLE
Duda citar chatGPT

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2133-PUC/2023-2#58]
Hola, en la parte de referencias quería saber que esperan de como referenciar lo obtenido en chatGPT. Por ejemplo, en mi caso del README.md puse lo siguiente:

1. Para la creación de los structs y modularización, me basé en el código de ejemplo del taller "basic-structs", siguiendo el ejemplo de los trenes y vagones.  
2. selectionSort fue obtenido de chatGPT (indicado en el código), pero modificado para adaptarlo a lo pedido en el enunciado.  
3. La manera de eliminar un nodo especifico en una lista ligada fue obtenida mediante chatGPT, utilizado en "DESERTAR", "ATACAR" (cuando hay que eliminar a un guerrero con 0 vida) y para "TRAICION" y "ALTA-TRAICION". En el caso de "ALTA-TRAICION", se modificó para que se pudiesen eliminar varios nodos a la vez.
4. En "ATACAR", las condiciones para obtener el escuadron con más ataque base sumado (y menor id en caso de empate) y el con menor cantidad de guerreros (y menor id en caso de empate), fueron obtenidos con chatGPT.
5. En "TRAICIONAR" las condiciones para obtener el escuadron con más guerreros fue obtenida de chatGPT.

Es suficiente con esto ?
De antemano muchas gracias !!

**Comment by CataAlamos** [comment]
Hola! Como estas citando esta bien, pero te sugiero no usar ChatGPT para hacer las tareas. Recuerda que la política de integridad académica ha cambiado y debes aprender como enfrentar estos enunciados tu.

**Comment by NicoJGutierrez** [comment]
Hola! Una pregunta de seguimiento. La política de integridad académica del enunciado prohibe cualquier ayuda de terceros, como se indica aquí:
![image](https://github.com/IIC2133-PUC/2023-2/assets/80768621/c19d3990-d09f-4e38-9850-b36f5cc8488b)
 

Eso hasta qué punto incluye chatgpt, considerado como una herramienta diseñada por terceros? 

Eso prohibiría que yo le pidiera ayuda a un amigo para debuguear mi código y encontrar un error que no pude encontrar por mi cuenta? 

Hasta qué punto esto prohibiría recibir ayuda de ayudantes, o prohibiría usar código de internet?

Esto para estar seguro de poder usar el código que usé, o revisar si tengo que hacer una nueva implementación.

**Comment by CarloGauss33** [comment]
Para dejarlo también más general:

Con apoyo de terceros, el código de honor se refiere a cualquier individuo externo al curso. Esta bien que compartan ideas de modelación con compañeros en el mismo curso, pero no pueden compartir código. La política de herramientas externas esta en el programa del curso y se puede resumir asi:

No requieren referienciar:
— Que ayude a encontrar algún bug
— Autocompletado de fragmentos de código (Por ejemplo copilot, pero sin solicitarle explícitamente que genere algo —completo)
— Código extraído desde el material del curso (Cápsulas, Talleres, Etc)

Requieren ser referenciado
- Código generado por otros programas (GPT, Copilot, Etc). Por ejemplo, si le pido a chatgpt que genere quicksort, y utilizo ese código copiando o basándome en tal. Se requiere referenciar.

Además, se asume que el estudiante entiende el código, y que se responsabiliza sobre el mismo. Por ejemplo, en caso de que exista sospecha de un caso de copia debido al uso de ChatGPT y se pregunta sobre la idea detrás de un método/algoritmo, no se considerara como válido decir “No entiendo por qué ChatGPT lo hizo”.

- Código extraído de internet (StackOverflow, GeeksForGeeks, Medium, etc). Y lo mismo, en caso de utilizarlo se debe referenciar y además entender
