### ISSUE TITLE
Dudas Output 

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2133-PUC/2023-2#59]
Hola!
En primer lugar disculpa por tanto texto ajaja.

Tengo la siguiente duda, ¿Se puede tener problemas en el output por no trabajar adecuadamente con la memoria?
Para verificar la correctitud de mis funciones primero las fui probando manualmente con ejemplos pequeños (por dar un ejemplo el mismo del diagrama del enunciado) y hacen lo esperado, pero al escalar la cantidad del input estoy teniendo errores.

Por dar un ejemplo:
Mi primer error en el test "B1 Easy" lo tengo en la línea 7411 del output, donde previamente se utilizan todas las funciones de la parte A y parte B (exceptuando ATACA), y visualmente ya descubrí mi error: para ese caso en el escuadrón 22 del ejército 0 ocurren los siguientes eventos: ENLISTAR, ENLISTAR, DESERTAR, ENLISTAR, por lo que tiene 2 guerreros (lo cual está correcto) y en mi output tengo solo 1 guerrero. Eso me llevo a pensar que quizás tenía un error de código donde el evento DESERTAR me bloqueaba la posibilidad de añadir nuevos guerreros, pero verifiqué que no era eso haciendo un ejemplo super pequeño: enlisté 3 guerreros, deserté a un guerrero y luego volví a enlistar otro guerrero y funcionó de manera correcta (pude enlistar ese último guerrero a ese respectivo escuadrón). Por lo que eso me llevo a mi duda de arriba: ¿Se puede tener problemas en el output por no trabajar adecuadamente con la memoria?

No le he prestado mucha atención al tema de la memoria pero creo que por ahí puede ir el problema porque mi función hace lo que debe hacer. Mi código más actualizado se encuentra en mi rama 'pendientes'. Feliz si me pueden orientar para resolver mi problema.

Reitero, disculpa por tanto texto. Intente detallar lo más posible la situación.

Quedo atento, y de antemano muchas gracias :)

**Comment by alvarocisternas** [comment]
Otra duda que me nació es la siguiente, ¿Si no tengo errores en los tests Hard A0, A1, A2 significa que mi error no está en la parte A?

**Comment by CataAlamos** [comment]
Hola! Para contestar tu segunda duda, claro lo mas probable es que el error este en la parte b. En cuanto a tu primera pregunta, los errores de memoria no van a afectar directamente el output(afectan el rendimiento y funcionamiento de tu código) pero lo más probable es que tengas un error en la lógica de tu código. Te sugiero explicarle tu código a tu mascota o un amigo, eso ayuda a que veas si hay un error ([Es esto](https://en.m.wikipedia.org/wiki/Rubber_duck_debugging)
