### ISSUE TITLE
Duda Parte A Equipar

### ISSUE THREAD

**Issue by JRichi99** [IIC2133-PUC/2023-2#6]
Hola buenas, en los input de equipar no se entrega un ejercito id. Solo se nos entrega un escuadron id, guerrero id y el bonus. 
Sin embargo, el escuadron id es relativo a un ejercito, por lo que entiendo que haria falta o ¿esta es una complejidad que nosotros tenemos que manejar?

Saludos

**Comment by CarloGauss33** [comment]
Actualizado el enunciado. Gracias por detectar
