### ISSUE TITLE
Duda evaluación

### ISSUE THREAD

**Issue by gonzaloi21** [IIC2133-PUC/2023-2#62]
Hola!
Para la parte práctica se evalúan los tests del servidor? O se incluyen mas?
Además, en el enunciado (página 11) dice: "Además la nota individual de cada parte se evalúa con la cantidad de tests correctos más 1"
Eso significa que podremos tener un test malo (y no perder puntaje) para cada parte (A, B y C)?
Gracias

**Comment by CataAlamos** [comment]
Hola! Tu nota depende de la cantidad de test cases que tengas correctos en cada parte, eso es lo que evaluamos en la parte práctica.

**Comment by Fernanda1232123** [comment]
si los tests me sale error por 1 línea de código, por ejemplo:
-  hay un salto de línea (y nada escrito) en el output.txt que no debería estar
- se repite la última instrucción y hay una línea de código repetida al final 
eso sifnifica que no tengo nada de puntaje?
