### ISSUE TITLE
Duda con documento de diseño (justificación)

### ISSUE THREAD

**Issue by bthompsonl** [IIC2133-PUC/2023-2#63]
No entiendo qué es lo que se espera que pongamos en el item de justificación del documento de diseño. Si por acá pudiesen dar una respuesta explicando de una forma más concreta se agradecería mucho :ok_hand:

**Comment by CataAlamos** [comment]
Hola! Esperamos que nos digamos porque estas haciendo algo, por ejemplo estoy modelando esto como una lista ligada porque no se el número total de elementos.
