### ISSUE TITLE
Repetición última fila test

### ISSUE THREAD

**Issue by MatiasMingo** [IIC2133-PUC/2023-2#64]
Hola.

En varias soluciones de los tests se repite la última fila. ¿Debemos implementar esa funcionalidad en nuestro código?
Por ejemplo en easy/A1.txt:
![Screen Shot 2023-08-30 at 20 04 19](https://github.com/IIC2133-PUC/2023-2/assets/20389726/8f4ebb45-681c-49d8-807b-055d8e8c0a79)

**Comment by ameliaiacobelli** [comment]
Hola! Tengo la misma pregunta. Los test me salen WRONG OUTPUT por esta razón.

**Comment by ibgarrido** [comment]
De hecho por eso yo preguntaba que me parecia raro que los test tuvieran N+1 eventos (el numero 'e' del enunciado) pero en realidad en el input.txt hay N-1 Eventos.

**Comment by ameliaiacobelli** [comment]
En el A1 de easy se que pasa

**Comment by ibgarrido** [comment]
> 

Hola! por lo que vi en el telegram ya solucionaron el problema!
