### ISSUE TITLE
Debugger MAC

### ISSUE THREAD

**Issue by aurzuav** [IIC2133-PUC/2023-2#66]
Alguien me puede ayudar con este error al debuggear con mac? Usé todo lo de la guía específico para mac y lo estoy corriendo dentro de la carpeta edd-docker con make start. Gracias.
 
![image](https://github.com/IIC2133-PUC/2023-2/assets/62019560/1310ec8d-f288-4a88-9332-94fd4e1bf581)

**Comment by aurzuav** [comment]
error completo:
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". Command 'exec-run'. Invalid process during debug session
The program '/Users/agustinurzua/edd-docker/volume/T0-2023-2-aurzuav/dcchueck' has exited with code 42 (0x0000002a).

launch.json
{
    // Generic C debug file for PUC IIC2133 For MacOS with CLang
    // by Carlos Paredes
    "version": "0.0.0",
    "configurations": [
      {
        "name": "CLang - Debug Executable",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceFolder}/volume/T0-2023-2-aurzuav/dcchueck",
        "args": ["{workspaceFolder}/volume/T0-2023-2-aurzuav/A1.txt", "{workspaceFolder}/volume/T0-2023-2-aurzuav/output.txt"],
        "stopAtEntry": true,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": false,
        "setupCommands": [
            {
                "description": "Enable pretty-printing for gdb",
                "text": "-enable-pretty-printing",
                "ignoreFailures": true
            }
        ],
        "MIMode": "lldb",
      }
    ]
  }

**Comment by aurzuav** [comment]
ayuda:(

**Comment by CarloGauss33** [comment]
Hola @aurzuav, el debugger no se ejcuta dentro de edd docker. Hace make clean && make desde la terminal normal. Y luego intenta de nuevo

**Comment by mati-gonz** [comment]
> Hola @aurzuav, el debugger no se ejcuta dentro de edd docker. Hace make clean && make desde la terminal normal. Y luego intenta de nuevo

Hola tuve el mismo problema (tengo Mac m1) y esto me ayudó a resolverlo. La duda que tengo es ¿Cada vez que quiera debuggear tendré que salirme de docker? Es que lo que he estado haciendo hasta ahora es probar mi código en docker solamente porque creo que no puedo hacerlo funcionar fuera de docker

**Comment by CarloGauss33** [comment]
Ósea es que Docker sirve principalmente para debuggear memoria con valgrind, mientras que el debugger es más general y por ende se ejecuta en mac directamente (Ya que o si no implicaria configurar vscode para que pueda ejecutar mediante docker)
