### ISSUE TITLE
Resultados de valgrind

### ISSUE THREAD

**Issue by agustind1** [IIC2133-PUC/2023-2#67]
Hola, tengo una duda con los resultados que me aparecen al ocupar valgrind, ya que si ejecuto el comando que aparece en el readme de la tarea me sale que tengo un error en un contexto y memoria sin liberar, pero cuando ocupo el comando que está en una de las guías (valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt ./executable input.txt output.txt) me aparece que no tengo ningún error y que no hay leaks posibles. A cual debería hacerle caso, y cómo puedo solucionar los errores de memoria en caso de que existan? (el programa me funciona bien y me devuelve los outputs esperados).

**Comment by benjavicente** [comment]
En el archivo que te genera ese comando no hay nada tampoco?

**Comment by agustind1** [comment]
En el archivo que genera el comando de la guía me aparece:
HEAP SUMMARY:
==24709==     in use at exit: 0 bytes in 0 blocks
==24709==   total heap usage: 12,454 allocs, 12,454 frees, 416,932 bytes allocated
==24709== 
==24709== All heap blocks were freed -- no leaks are possible
==24709== 
==24709== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==24709== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
(y arriba de eso muchas redirecciones, tipo --24709-- REDIR: 0x4ed5910 (libc.so.6:free) redirected to 0x4c32cd0 (free))



Mientras que con el comando del readme me aparece en consola:
==5600== Memcheck, a memory error detector
==5600== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==5600== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==5600== Command: ./dcchueck input output
==5600== 
==5600== Invalid read of size 4
==5600==    at 0x4EBA1FD: __isoc99_fscanf (isoc99_fscanf.c:30)
==5600==    by 0x108AA7: main (main.c:66)
==5600==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==5600== 
==5600== 
==5600== Process terminating with default action of signal 11 (SIGSEGV)
==5600==  Access not within mapped region at address 0x0
==5600==    at 0x4EBA1FD: __isoc99_fscanf (isoc99_fscanf.c:30)
==5600==    by 0x108AA7: main (main.c:66)
==5600==  If you believe this happened as a result of a stack
==5600==  overflow in your program's main thread (unlikely but
==5600==  possible), you can try to increase the size of the
==5600==  main thread stack using the --main-stacksize= flag.
==5600==  The main thread stack size used in this run was 8388608.
==5600== 
==5600== HEAP SUMMARY:
==5600==     in use at exit: 552 bytes in 1 blocks
==5600==   total heap usage: 2 allocs, 1 frees, 1,104 bytes allocated
==5600== 
==5600== LEAK SUMMARY:
==5600==    definitely lost: 0 bytes in 0 blocks
==5600==    indirectly lost: 0 bytes in 0 blocks
==5600==      possibly lost: 0 bytes in 0 blocks
==5600==    still reachable: 552 bytes in 1 blocks
==5600==         suppressed: 0 bytes in 0 blocks
==5600== Rerun with --leak-check=full to see details of leaked memory
==5600== 
==5600== For counts of detected and suppressed errors, rerun with: -v
==5600== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault

**Comment by benjavicente** [comment]
Está raro, puede que uno de los argumentos pasados en la guía deshabilité una opción de valgrind que ve lecturas inválidas (en la guía es full leaks y en lo segundo es como general).

Revisa lo segundo (sin argumentos) con el error de

```txt
==5600== Invalid read of size 4
==5600== at 0x4EBA1FD: __isoc99_fscanf (isoc99_fscanf.c:30)
==5600== by 0x108AA7: main (main.c:66)
==5600== Address 0x0 is not stack'd, malloc'd or (recently) free'd
```

**Comment by agustind1** [comment]
Cómo puedo descubrir qué es lo que está mal en ese caso?

**Comment by benjavicente** [comment]
Puedes usar un debugger o ver cuáles son los valores que tienes antes de llegar a la línea que se muestra en el error.

**Comment by CarloGauss33** [comment]
El error que tienes de 
```
==5600== Invalid read of size 4
==5600== at 0x4EBA1FD: __isoc99_fscanf (isoc99_fscanf.c:30)
==5600== by 0x108AA7: main (main.c:66)
==5600== Address 0x0 is not stack'd, malloc'd or (recently) free'd
```

Es debido a que le estas pasando mal el path a los archivos de input, y por ende intenta leer y crashea

**Comment by agustind1** [comment]
> 

Hola carlos, no entiendo bien que quiere decir eso, no es un error de código entonces?

**Comment by CarloGauss33** [comment]
Hola @agustind1. Es simplemente que la ruta al archivo de input esta mal escrita al ejecutarlo con valgrind
