### ISSUE TITLE
Atributos guerreros

### ISSUE THREAD

**Issue by arturoprietovic** [IIC2133-PUC/2023-2#69]
Al hacer traición o Alta Traición se deben actualizar los atributos de los guerreros a su nuevo ejercito y escuadrón?
Porque probé test del hard y funciona todo bien sin cambiarle los atributos.
Gracias

**Comment by CarloGauss33** [comment]
¿Como atributos? Recuerda que toda la modelación de structs y si tendran o no atributos depende de tu tarea. El ejército y escuadrón es solo una forma de identificar a que pertenece. Pero el resto depende de como modelaste tu tarea

**Comment by arturoprietovic** [comment]
ok gracias
