### ISSUE TITLE
Vida de un guerrero y formato input

### ISSUE THREAD

**Issue by agustinbc7** [IIC2133-PUC/2023-2#7]
Hola, tengo 2 dudas:
¿Cómo se cuál es la vida que tiene cada guerrero? No aparece en Enlistar ni tampoco sale una vida base en el enunciado.

Con respecto al formato del input de enlistar, aparece que el quinto parámetro será el id de la facción, pero en el ejemplo colocan el nombre, entonces no comprendo si pondrán el id o el nombre.

Gracias de antemano.

**Comment by CarloGauss33** [comment]
Hola @agustinbc7 en ambos casos faltaba detallar en el enuciado. ambos fueron corregidos (el campo de vida y el formato de input)
