### ISSUE TITLE
Problema con servidor

### ISSUE THREAD

**Issue by FelipeRiveraC** [IIC2133-PUC/2023-2#70]
Hola a todos.

He realizado la tarea y corrdido los test numerosas veses a mano y comparando con diffchecker. Sin embargo el servidor me los arroja como malos. (WRONG OUTPUT) cuando yo se que esto es falso.*

Alguien puede ayudarme con esto porfavorr?

**Comment by CarloGauss33** [comment]
Hola! ¿Que te dice `diff -b` via consola o la herramienta `eddcmp`? Además, estas probando en /test? O en /grade? Finalmente revisa si es que tu git esta actualizado a la ultima ultima versión

**Comment by CataAlamos** [comment]
Hola, al usar diff en local te da diferencias? En caso de que no, quita los prints que no son necesarios que es típico usar para debug.

**Comment by FelipeRiveraC** [comment]
Tengo en master mis cambios mas actualizados. Los output son identicos, lo he testeado rigurosamente. Tampoco tengo prints inesesarios. Voy a probar con la herramienta `eddcmp`, les cuento como me va.

**Comment by CarloGauss33** [comment]
Y estas probando en `/test` en el server o en `/grade`?

**Comment by FelipeRiveraC** [comment]
@CarloGauss33 Estoy probando en `/test` acabo de usar la herramienta `eddcmp` y me arroja que ambos output son identicos.

**Comment by CarloGauss33** [comment]
¿Cuales tests son? para revisar en el server con tu repo

**Comment by FelipeRiveraC** [comment]
Son varios, pero para darte uno concreto:
`|              hard-B2 |         WRONG OUTPUT |                    0 |                 2.08 |`

**Comment by FelipeRiveraC** [comment]
```
~/Desktop/Otros/edd/T0-2023-2-FelipeRiveraC master
❯ ./dcchueck B2-HARD.txt output.txt

~/Desktop/Otros/edd/T0-2023-2-FelipeRiveraC master
❯ eddcmp B2-HARD-SOL.txt output.txt
```

Dejo comparacion del B2-HARD

**Comment by CarloGauss33** [comment]
Tienes muchos errores de memoria que generan `Conditional jump or move depends on uninitialised value`  Esto provoca que tu output de un valor correspondiente a NULL en una variable. Te recomiendo revisar con valgrind y solucionar estos problemas (Cuando aparece lo de conditional jump implica que el programa utilizara lo que se encuentre en memoria en ese momento, y por ende el resultado dependerá del sistema operativo, programas abiertos, que se ejecuto antes, etc)

<img width="281" alt="image" src="https://github.com/IIC2133-PUC/2023-2/assets/45949389/2d6ccdc7-ee22-4380-9d7e-628d7f32987c">

**Comment by FelipeRiveraC** [comment]
Gracias @CarloGauss33 , no habia usado valgrind.

**Comment by FelipeRiveraC** [comment]
Tengo un Macbook m2, hay alguna alternativa a valgrind con ARM?

**Comment by CarloGauss33** [comment]
tienes que ejecutar `make clean && make` si es que ejecutaras dentro de docker

**Comment by FelipeRiveraC** [comment]
@CarloGauss33 Gracias carlos, ya mis test pasan. Gracias por la ayuda.
