### ISSUE TITLE
Problemas con ingresar al Servidor

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2133-PUC/2023-2#71]
Hola!!
No me resulta ingresar al servidor.
Adjunto comando que estoy intentando ejecutar
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/8f38af8e-673e-4509-8bb1-130e5750868c)

**Comment by CarloGauss33** [comment]
Hola @Fernanda1232123, no es un comando. Es un enlace, por lo que hay que ingresarlo en el navegador

**Comment by Fernanda1232123** [comment]
Buenísimo muchas gracias, me resultó.

Tengo otra duda, me sale WRONG OUTPUT en todos, pero mis outputs están buenos. Me funciona bien:
ENLISTAR
EQUIPAR
CONTEO-CAMPAL
ORDEN-EJERCITO
DESERTAR
eso es lo que tengo programado y todo me sale exactamente como quiero. Así que quizás no estoy entendiendo completamente el output que debiera dar, ¿como puedo arreglarlo? ¿como puedo comparar para ver que esté entendiendo bien el output que me debiera dar?

Gracias!!

**Comment by CataAlamos** [comment]
Hola! Hiciste uso de `diff output_esperado.txt output_tuyo.txt`? Con eso puedes ver si hay diferencias entre dos archivos.

**Comment by Fernanda1232123** [comment]
que debería poner en outout_esperado.txt?? ¿así tal cual eso "output_esperado"? ¿debo ejecutar algo antes de eso para que funcione (aparte de make)? 
Gracias por responder tan rápido!!!

**Comment by Fernanda1232123** [comment]
y donde se hace uso de diff output_esperado.txt output.mio.txt?? ¿en la consola o en el servidor?

**Comment by CataAlamos** [comment]
Hola! Nosotros te dimos los outputs correctos de los test cases, eso es el output esperado, y el output que tienes tu al correr el mismo test case pero con tu código es el output tuyo. 
Esto se corre de forma local, y el path ya depende de donde tengas tu archivos.

**Comment by Fernanda1232123** [comment]
ahh ya entendí!!! jajaj cuando miré eso en el drive no entendía para qué eran
gracias, voy a intentar ahora
