### ISSUE TITLE
Problemas Invalid write/read

### ISSUE THREAD

**Issue by TomasAltermatt** [IIC2133-PUC/2023-2#72]
Hola, estuve probando mi código con el servidor con /grade y en los tests B1 me tiran los mismos errores de Invalid read o Invalid write. He estado un rato tratando de encontrar qué pasa y no lo pillo. No sé si los ayudantes tienen acceso a mi repositorio, por si me pueden ayudar.

Gracias de antemano

**Comment by CataAlamos** [comment]
Hola! Lo mas probable es que estas escribiendo mal un archivo y/o le leyendolo mal, revisa bien `scanf` y `fprintf`

**Comment by TomasAltermatt** [comment]
Eso sí lo revisé, pero probé los tests B2 y solo me arroja WRONG OUTPUT, así que supuse que no era ese el problema. Los errores son de este estilo

![image](https://github.com/IIC2133-PUC/2023-2/assets/127430537/d7897b27-fcc0-4b2e-b466-08f010b0ac66)

**Comment by CataAlamos** [comment]
Hola! Claro los errores que tienes te están dando el WRONG OUTPUT, para que este correcto no debe haber errores en tu código.

**Comment by TomasAltermatt** [comment]
Entiendo eso, y estuve buscando en las secciones de mi código donde hago los free, pero logro encontrar por qué me tiran esos errores

**Comment by illanes00** [comment]
Hola! Te recomiendo ver[ cómo leer los mensajes de error](https://github.com/IIC2133-PUC/2023-2/blob/master/Gu%C3%ADas/5.%20AYUDAA%20(Gu%C3%ADa%20de%20resoluci%C3%B3n%20de%20problemas%20en%20tareas).md#c%C3%B3mo-leer-el-output-de-valdgrind). Ahí podrás ver en qué línea en específico de tu código puedes encontrar tu error
