### ISSUE TITLE
DUDA servidor COMPILATION ERROR

### ISSUE THREAD

**Issue by rvcruz** [IIC2133-PUC/2023-2#74]
Hola! al momento de utilizar el comando grade del servidor, el resultado me entrega compilación error, lo anterior me entrega una tabla vacia de intentos. ¿Me pueden ayudar?

**Comment by illanes00** [comment]
Hola! ¿Viste la [guía de errores comunes](https://github.com/IIC2133-PUC/2023-2/blob/master/Gu%C3%ADas/5.%20AYUDAA%20(Gu%C3%ADa%20de%20resoluci%C3%B3n%20de%20problemas%20en%20tareas).md#6-anexo-mi-c%C3%B3digo-est%C3%A1-perfecto-pero-el-servidor-lo-corrige-mal-qu%C3%A9-hago)?

**Comment by rvcruz** [comment]
Al trabajar en mi computador, realice la modulación respecto a mi path. Al subirlo al servidor, debo tener cuidado con este aspecto. Ya lo he solucionado.
