### ISSUE TITLE
dudas evaluación

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2133-PUC/2023-2#75]
Hola!!

Ejecutando diff tengo los siguientes tests iguales:
easy:
A0->bien!
A1->bien!
A2->bien!
medium:
A01->bien!
A11->bien!
A21->bien!
Hard:
A12->está todo ok, excepto que en "output.txt" hay un salto de línea al final. Pero está todo lo escrito bien
A02->está todo ok, excepto que en "output.txt" hay un salto de línea al final. Pero está todo lo escrito bien
A22->está todo ok, excepto que en "output.txt" hay un salto de línea al final. Pero está todo lo escrito bien
easy:
B0->bien!
...
El resto tengo algunos problemas, entre ellos segmentation fault. 

Pero al correr en el servidor me sale que tengo todos los tests malos. ¿Por qué puede ser? 

La diferencia del salto de línea de la última línea en A12, A02, A22 me parece raro porque todos los tests que tengo buenos sí tienen ese salto de línea, entonces esos tests sí tienen ese salto de línea. Solo me sale error en los tests mencionados. Recalco que todo lo escrito está bien.

Además, si hay un error de una línea, son 0 puntos???

**Comment by CataAlamos** [comment]
Hola! Te sugiero revisar bien si los test cases que tienes buenos tienen algún error, puedes usar valgrind. Respecto a lo otro tendrás 0 puntos hasta que mandes a recorregir donde tu puntaje **puede** cambiar pero no te lo podemos garantizar. Te sugiero revisar la guía de errores comunes(#42) esto te puede ayudar al momento de debug.

**Comment by Fernanda1232123** [comment]
Hola! Valgrind me sale que no tengo errores ni leaks de memoria.
Tengo hasta DESERTA implementado, y todo eso funciona bien

**Comment by Fernanda1232123** [comment]
En todo caso, esos resultados de tests están distintos por ese salto de línea (A1 hard, A0 hard , A2 hard; en mi código corresponden a A22, A12, A02). Adjunto foto de A22 de mi output y del resultado para ver la diferencia y el error que me da en la terminal. Y adjunto foto de medium A2 donde se puede ver que el resultado sí tiene salto de línea, que corresponde a A21 en mi código. 

![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/56479f49-2203-42b6-8776-21fbe28e8a31)
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/013b4760-28cf-40a9-99a5-f6019816c23c)
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/8e6fe3bb-497f-4621-9cdf-70fbf7b1915c)
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/37654459-a59b-4e06-a2fb-eb2e86d6b3d3)
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/3719993a-acb7-406d-a430-81bd8ba7927d)
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/bec6b387-cb90-4b41-9685-badc574e97fb)

Además, el puntaje de no errores en memoria y no leaks en memoria, si valgrind me sale todo OK (no hay leaks ni errores) pero tengo segmentation fault en los tests medium y hard de B, debería tener todo el puntaje?

**Comment by CataAlamos** [comment]
Si tienes segmentation fault entonces tienes errores de memoria, por lo que no tendrías puntaje completo.

**Comment by CarloGauss33** [comment]
Hola @Fernanda1232123 el salto de linea no afecta. Se corrige con [eddcmp](https://github.com/IIC2133-PUC/eddcmp). que evita problemas de formato (Tmb puedes usar diff -b) en tu computador. 


Valgrind te dice algo? Si sale en el server mal puede ser porque hay memoria no inicializada

**Comment by Fernanda1232123** [comment]
con valgrind solo tengo problemas en los B de medium y hard, y C. Los B1 y B2 easy tengo unas diferencias, así que estaría mal la implementación. Todos los A y B0 easy me funcionan perfecto localmente, probado con diff. A excepción de los saltos de línea al final de A hard. Aún así, en el servidor me salen todos los tests malos.

diff -b me dice que no existe el comando -b.
¿Como se usa eddcmp?

**Comment by CataAlamos** [comment]
En la repo de eddcmp en el README dice como funciona. Me podrías mostrar lo que te muestra valgrind cuando corres un test A?

**Comment by CarloGauss33** [comment]
mmm que raro que diff diga que no existe el -b. tienes captura de ese output para ver que onda?

**Comment by Fernanda1232123** [comment]
Aquí van las fotos. El comando -b funcionó finalmente, no sé por qué no había funcionado antes. 
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/f86ac89d-5733-498e-a9f6-c5fce0a0cf39)
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/091173ef-c546-4cf6-9c0a-db7f0eed3891)

**Comment by CataAlamos** [comment]
Puedes mostrar que te da cuando usas valgrind en un test case A?

**Comment by Fernanda1232123** [comment]
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/56ff41c1-6791-4473-b42a-c07680e8a4f3)
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/64be1dc3-520a-4e12-ba17-7f30483515e3)
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/20416620-0958-46a2-9838-e95c108b959b)
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/a874f71e-e8c4-4e80-8d98-12409a9e08ca)
![image](https://github.com/IIC2133-PUC/2023-2/assets/89221305/9fd0ed67-8b10-4105-a946-82b7eb9de567)

**Comment by CataAlamos** [comment]
Mira las fotos, te dice que no todos los errores de memoria estan siendo reportados, estas usando edd docker o edd runner?

**Comment by Fernanda1232123** [comment]
Como se usan?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CarloGauss33** [comment]
Hola @Fernanda1232123 al final el problema no era valgrind. El problema es que tienes la ruta de output hardcodeada. (siempre se escribe el out a un archivo llamado output.txt en vez del archivo que se pasa por input)

**Comment by CarloGauss33** [comment]
@Fernanda1232123 lo del enunciado se refiere a que el archivo de output es un argumento del programa.
A lo que me refiero es que se debe usar el FILE* output_file = .... tal como viene en el codigo base (que carga el nombre desde los argv)

**Comment by Fernanda1232123** [comment]
ah ya creo que entendí, voy a ver si puedo cambiarlo

**Comment by Fernanda1232123** [comment]
Estoy teniendo el mismo problema de WRONG OUTPUT aunque hice el cambio. ¿Qué puede ser?
