### ISSUE TITLE
Salto de linea (\n) al final del output

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2133-PUC/2023-2#76]
Hola!! 

ya terminé de pasar todos los tests pero hay un problema de inconsistencia entre la solución de los tests easy y los tests hard. Al debuggear los tests hard, noté que el único error que tenía era que algunos eventos agregaban un salto de linea al final del output, pero si uno de esos eventos es el ultimo en recibir el programa, se agregaba un salto de linea al final del output que el archivo de solución no tenía.

Solucioné esos eventos para no agregar el ultimo salto de linea en el caso de ser el ultimo evento en ser llamado, sin embargo, ahora los tests easy me dan distintos porque estos tests si tienen el salto de linea al final.

De este modo, el mismo evento en los tests easy tiene que tener un salto de linea al final pero en los tests hard no tiene que tener el salto de linea al final. La única forma de solucionar esto es identificar si estamos en un test easy o hard y agregar/quitar el ultimo salto de linea según sea el caso, pero me imagino que esto debe ser un error de formato de la solución y no de mi código.  Quedo atento para saber si dejarlo con el ultimo salto de linea o sin o si tengo que manejar cada caso.

muchas gracias !

**Comment by CarloGauss33** [comment]
Hola. Los saltos de línea no afectan (Tampoco los trailing whitespaces). En el curso corregimos con una herramienta propia que evita esos problemas [eddcmp](github.com/IIC2133-PUC/eddcmp) También puedes usar diff -b para verificar
