### ISSUE TITLE
problemas debugger

### ISSUE THREAD

**Issue by brayan788** [IIC2133-PUC/2023-2#8]
hola estaba intentando utilizar el debugger que aparece en la capsula, al intentar correrlo me dice "Unable to start debugging. The value of midebuggerpath is invalid", intente cambiarlo y al preguntar por consola "which gdb" me entrega el mismo path que esta en el archivo .json, nose que puede estar mal, ya que me deja ejecutar gdb por consola pero es menos amigable. Estoy en wsl.

**Comment by CarloGauss33** [comment]
Pregunta, estas ejecutando VScode mediante la extensión que permite que sea abierto dentro de wsl? (Abajo a la izquierda deberia aparecer algo como > Remote WSL

**Comment by brayan788** [comment]
no, estoy sin la ventana remota de vscode, tengo que abrir las carpetas ahi para que funcione el debugger?

**Comment by Pakarati** [comment]
@brayan788 Siii, de lo contrario no podrás debuggear ni ejecutar correctamente tu tarea (necesitas estar trabajando en el ambiente de wsl). Prueba con eso:))
