### ISSUE TITLE
Duda cantidad de ejercitos

### ISSUE THREAD

**Issue by mjadresic** [IIC2133-PUC/2023-2#9]
Hola, al principio del enunciado dice que hay solamente 2 ejercitos:
En este conflicto dramático existen dos ejércitos, el ejército del reino DCChueck (que tendrá ID 0) y el
ejército de Farquaad (que tendrá ID 1)

Luego dice que el formato para ENLISTAR es:
ENLISTAR ejercitoID escuadronID guerreroID dañoBase faccionID capacidadArsenal

Pero en la linea 7 del ejemplo de input que dan, dice:
ENLISTAR 5 1 100 2 CAPASDECEBOLLAS 9

Es decir, ejercitoID = 5. Entonces mi duda es si esto es un error del ejemplo o si es que si pueden haber ejercitos con otros ID.

**Comment by CarloGauss33** [comment]
Hola @mjadresic El enunciado fue actualizado, La ultima versión se encuentra con eso parchado. Sobre lo de ejercitoID 5 lo revisare, posiblemente se nos paso

slds
