### ISSUE TITLE
[T1] command-line error: language modes specified are incompatible

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2133-PUC/2023-2#97]
Hola, al crear un módulo "quadTree" dentro de "hadaCompress" me sale el error "command-line error: language modes specified are incompatible". Este es el directorio en el que creé mi módulo:
![image](https://github.com/IIC2133-PUC/2023-2/assets/80768621/dbcc93a6-7928-44be-9561-fce15c948096)
Quizá tenga que agregar algo al makefile (?) pero la verdad es que están creados de la misma manera que para bstRey...

**Comment by NicoJGutierrez** [comment]
(es un error que me sale de vscode)

**Comment by NicoJGutierrez** [comment]
Acá me aparece el error:
![image](https://github.com/IIC2133-PUC/2023-2/assets/80768621/8f4962f4-0f6d-4522-8e81-f1d71e554b57)

**Comment by CarloGauss33** [comment]
Eso tiene pinta de ser problema de configuración de VSCode en si. Has utilizado la extension anteriormente?

**Comment by NicoJGutierrez** [comment]
Al final como buen problema de configuración se arregló reiniciando el compu.
