### ISSUE TITLE
Servidor no entrega resultados

### ISSUE THREAD

**Issue by Francescorodriguezg** [IIC2133-PUC/2023-2#98]
Hola!
Anoche tipo 10 pm intenté probar mi codigo en el servidor (modalidad test), pero los resultados aun no aparecen. Está funcionando?
Gracias de antemano

**Comment by CarloGauss33** [comment]
El server esta bueno pero con problemas de disponibilidad y mucho sobreuso. POr lo que es recomendable intentar cada ciertas horas
